export const AUTH_SUCCESS = "LOG_IN_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const FETCH_SCHOOL_LIST_SUCCESS = "FETCH_SCHOOL_LIST_SUCCESS";